---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: cv-latex.tex
geometry: 'left=0.5in,top=0.3in,right=0.5in,bottom=0.3in'

title: 'Resume'
author: Xiao (Seanny) Song

fontawesome: true

jobtitle: Data Analyst
email: 'songxiao@umd.edu'


github: 'songxxiao'
web: 'xsong.ltd'
linkedin: 'seannysong'
# twitter: -----
phone: '2405641321'


# keywords: R Markdown, academic CV, template
fontfamily: Palatino # TeX Gyre Pagella  # mathpazo  Palatino
# fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: black

---

# EDUCATION

**Robert H. Smith School of Business, University of Maryland**, College Park, MD \hfill 2021~Present   
Master of Business Analytics 

**East China Normal University**, Shanghai \hfill 2016~2020  
Bachelor of Sociology 

# WORK EXPERIENCE

**FancyDigital**, Shanghai \hfill 2020-09~2021-04  
*Data Analyst(Full-Time)*

+ Built BI dashboards to visualize customers' features and daily revenue of a SaaS system resulting in a 5% growth of customers

+ Performed user churn analysis based on users databases and provided user service suggestions to operators resulting in a decrease of user churn rate to 10%

+ Worked alongside product managers to optimize product design and user experience  using error logs data that reduced bug rate by 7%

+ Wrote ETL shell scripts to aggregate original detailed data tables into intermediate tables which increase query performance by 85%

<!---
+ Use distributed OLAP databases such as Apache Doris/TiDB/Clickhouse to write BI data dashboards. Use a variety of visualization methods to show usage and revenue of system. Count consumption of advertising in multiple dimensions, such as time and user dimensions
--->



**Zhongnan University of Economics and Law**, Remote \hfill 2020-02~2020-04   
*Data Scientist Internship*

+ Trained a 5 folds cross validation model to predict likelihood of a legal provision's category and obtained improvement of accuracy to 0.8 

+ Preformed word frequency method and several NLP methods to construct feature matrix and built a reverse-translation method to augment training dataset that increase test accuracy by 5%

**iResearch Consulting**, Shanghai \hfill 2019-07~2019-10   
*Data Analyst Internship*

+ Applied cluster analysis method to develop vehicle user profile and provide marketing advice for customers in the automotive industry

<!---
+ Compiled consulting reports based on data analysis according to user portraits to help automobile manufacturers establish product positioning for target users
--->

# AWARDS AND HONORS

**Kaggle** [**M5 Forecasting - Accuracy**](https://www.kaggle.com/c/m5-forecasting-accuracy) \qquad 103rd/5558 \ Top2% \ Silver Medal \hfill 2020    
*Estimate unit sales of Walmart retail goods*   

+ Created features on tabular data and trained a LightGBM algorithm to forecast daily sales for next 28 days and acquired 0.58 of RMSE

+ Stacked and averaged single LightGBM model predictions to improve the generalization ability of forecasts which promoted 10% of ranking on leaderboard

<!---
**Kaggle** [**M5 Forecasting - Uncertainty**](https://www.kaggle.com/c/m5-forecasting-uncertainty) \qquad 18th/909 \ Top2% \ Silver Medal  \hfill 2020  
*Estimate  uncertainty distribution of Walmart unit sales*   
--->

# TECHNICAL SKILLS

+ Python (Numpy, Pandas, Scikit-learn, Keras), R
+ Tableau, SQL(MySQL, SQL Server, TiDB, Clickhouse), Linux/Shell, SPSS, Stata, Git, \LaTeX, HTML/CSS
+ Web Crawler
+ Text Mining



<!---
+ **Database / Data Warehouse** Good at writing and optimization of sql commands based on MySQL, SQL Server, etc. Familiar with advanced methods such as window functions

+ **Data Analytics & Statistics** Familiar with data manipulation and statistical analysis based on Python and R language, including use of software packages such as `numpy`, `pandas` and `data.table`, `tidyverse`

+ **Machine Learning** Familiar with  ory and application of traditional machine learning methods, including cross-validation training and parameter adjustment based on `sklearn`'s Logistic Regression, SVM, Xgboost and or models

+ **Data visualization** Proficient in using Tableau, `ggplot2`, `plotly` and or software packages to visualize discrete data and continuous data, and be good at making dashboards based on business logic

+ **Web Crawler**  Familiar with  basic knowledge of html/css/json, can use Selenium, bs4 and or tools in Python to crawl data presented in  webpage and write it into  database for storage

+ **Other Skills**  

Python (NumPy, Pandas, Scikit-learn, Keras, Flask), Tableau, 
SQL(MySQL, SQL Server, TiDB, Clickhouse), Linux/Shell, SPSS, Stata, Git, \LaTeX, HTML/CSS

<!---

**Data Analytics**  
Familiar with  principle and implementation of statistical analysis in R language, able to use `tidyverse`, `data.table` for data cleaning.  
Understand R language statistical analysis, derivation and implementation of LR, RNN, generalized linear model, K-means and or methods.  
Familiar with Python `pandas` library for manipulation of tabular data, `numpy` library for numerical operations.

**Data visualization**  
Familiar with R language `ggplot2`, Python `seaborn` `plotnine` library.

**Machine Learning**  
Understand  principles and implementation of Xgboost, LightGBM and or high-performance algorithms.  
Familiar with  implementation of various algorithms of Python `sklearn` library, including supervised learning and unsupervised learning.  
Understand  principles and implementation of natural language processing using `keras` deep learning framework.

**Big Data**  
Understand how to use R language `sparklyr` and or tools to connect and operate Hadoop and Spark clusters

**Standard Examination**  
TOEFL \quad 103 \ *Reading* 29 *Listening* 27 *Speaking* 21 *Writing* 26  
GRE \quad *Verbal*  154 *Quantity* 167 *Writing* 3.5

SQL, SPSS, Stata, Git, \LaTeX, MS Office, HTML/CSS
--->



















